language: c

os:
  - linux
    dist: trusty
    sudo: required
  - osx

compiler:
  - gcc
  - clang

before_install:
- echo "Building for $TRAVIS_OS_NAME\n";

#Linux
if [ $TRAVIS_OS_NAME == linux ]; then
  sudo apt-get update -qq;
  sudo apt-get install gettext;
fi

script: ./autogen.sh --git-build
